name: CI

on: pull_request

jobs:

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Lint check
      run: npm run lint

  test-latest:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test with Angular@latest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib
      run: npm run build
    - name: Run unit tests
      run: npm run test:unit:${{ matrix.os }}
    - name: Run unit tests in private mode
      run: npm run test:unit:${{ matrix.os }}:private
    - name: Install matching webdriver version
      run: ./node_modules/.bin/webdriver-manager update --versions.chrome 77.0.3865.40
      if: matrix.os == 'ubuntu-latest'
    - name: Run general e2e tests
      run: npm run test:e2e:demo
      if: matrix.os == 'ubuntu-latest'
    - name: Run interoperability e2e tests
      run: npm run test:e2e:interoperability
      if: matrix.os == 'ubuntu-latest'
    - name: Run Ivy e2e tests
      run: npm run test:ivy
      if: matrix.os == 'ubuntu-latest'

  test-next:

    name: Test with Angular@next
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build the lib (with the current version, as it is what is published on npm)
      run: npm run build
    - name: Update dependencies to next version
      run: npm install @angular/common@next @angular/compiler@next @angular/core@next @angular/platform-browser@next @angular/platform-browser-dynamic@next @angular/router@next @angular/cli@next @angular/compiler-cli@next @angular-devkit/build-angular@next @angular-devkit/build-ng-packagr@next
      env:
        CI: true
    - name: Run unit tests
      run: npm run test:unit:ubuntu-latest
    - name: Run unit tests in private mode
      run: npm run test:unit:ubuntu-latest:private
    - name: Install matching webdriver version
      run: ./node_modules/.bin/webdriver-manager update --versions.chrome 77.0.3865.40
    - name: Run general e2e tests
      run: npm run test:e2e:demo
    - name: Run interoperability e2e tests
      run: npm run test:e2e:interoperability
    - name: Run Ivy e2e tests
      run: npm run test:ivy
